name: release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x

    - name: Build binaries
      run: dotnet fsi ./src/make_release.fsx build

    - uses: actions/upload-artifact@v2
      with:
        name: release-binaries
        path: |
          release/*.tar.gz
          release/*.zip

  checksum:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - uses: actions/download-artifact@v2
      with:
        name: release-binaries
        path: release/

    - name: Checksum binaries
      run: dotnet fsi ./src/make_release.fsx hash

    - uses: actions/upload-artifact@v2
      with:
        name: release-binaries
        path: |
          release/*.tar.gz
          release/*.zip
          release/*.txt
